<%@ Page Title="" Language="C#" MasterPageFile="~/SundaySchool.Master" AutoEventWireup="true" CodeBehind="CommunionViewForm.aspx.cs" Inherits="Diocese.CommunionViewForm" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
      <asp:LinkButton ID="LnkbtnHome" runat="server" OnClick="LnkbtnHome_Click">Back to Home</asp:LinkButton>
  
   <div>
        <table>
            <tr>
                <th><label class="control-label">Date of Communion</label>
                <input type="date" id="dateofcommunion" class="form-control1 ng-invalid ng-invalid-required" ng-model="model.date" required="" onchange="date_dis()">
                <asp:hiddenfield ID="hid_docommunion" runat="server"></asp:hiddenfield></th>      
              <th style="padding-left:2px;"><asp:ImageButton ID="Imgbtnsearch" runat="server" OnClick="Imgbtnsearch_Click"                                       ImageUrl="~/images/search.png" Width="20px"/></th>
            </tr>
            <tr><th><asp:TextBox ID="TBPriestname" runat="server"></asp:TextBox></th></tr>
        </table>
    </div>
    <div style="margin-left:70%">

            <asp:Label runat="server" ID="LBL_NumberOfMF"></asp:Label>
    </div>
    <asp:gridview runat="server" id="GVCommuniondetails" AutoGenerateDeleteButton="True" 
          onrowdeleting="GVCommuniondetails_RowDeleting"    
 AutoGenerateColumns="False" CellPadding="4" DataKeyNames="Communion_ID" OnRowDataBound="GVCommuniondetails_RowDataBound" ForeColor="#333333" GridLines="None" Width="881px" >
        <AlternatingRowStyle BackColor="White" />
        <Columns>
            <asp:TemplateField HeaderText="Family Name" SortExpression="Family Name">
                <ItemTemplate>  <asp:Label ID="LBLFamilyName" runat="server" Text='<%# Bind("FamilyName") %>'></asp:Label>
                           </ItemTemplate>
            </asp:TemplateField>
             
            <asp:BoundField DataField="Parish_id" HeaderText="Parish_id" SortExpression="Parish_id" visible="false"/>
        
            <asp:TemplateField HeaderText="Official Name" SortExpression="Official Name">
                <ItemTemplate>  <asp:Label ID="LBLOfficialName" runat="server" Text='<%# Bind("OfficialName") %>'></asp:Label>
                           </ItemTemplate>
            </asp:TemplateField>
              <asp:TemplateField HeaderText="Baptism Name"  SortExpression="Baptism Name">
                <ItemTemplate>  <asp:Label ID="LBLBaptismName" runat="server" Text='<%# Bind("BaptismName") %>'></asp:Label>
                           </ItemTemplate>
            </asp:TemplateField>
              
            <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />

              <asp:TemplateField HeaderText="Communion Date" SortExpression="Gender">
                <ItemTemplate>  <asp:Label ID="LBLDOFCommunion" runat="server" Text='<%# Bind("DO_communion") %>'></asp:Label>
                           </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Action" SortExpression="Action">
                <ItemTemplate>
                    <asp:LinkButton ID="LNK_dnldCertificate" OnClick="LNK_dnldCertificate_Click" runat="server" Visible="true" CommandArgument='<%#Eval("Communion_ID")%>'>Download Certificate</asp:LinkButton>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <EditRowStyle BackColor="#2461BF" />
        <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#EFF3FB" />
        <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F5F7FB" />
        <SortedAscendingHeaderStyle BackColor="#6D95E1" />
        <SortedDescendingCellStyle BackColor="#E9EBEF" />
        <SortedDescendingHeaderStyle BackColor="#4870BE" />
    </asp:gridview>
    <br />

     <script type="text/javascript">
     function date_dis()
        {
            var textbox = document.getElementById('dateofcommunion');
            document.getElementById('<%=hid_docommunion.ClientID%>').value = textbox.value;
            alert(textbox.value);

        }
       </script>
</asp:Content>
