<%@ Page Title="" Language="C#" MasterPageFile="~/MemberMaster.Master" AutoEventWireup="true" CodeBehind="Member_ViewNotification.aspx.cs" Inherits="Diocese.Member_ViewNotification" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div id="page-wrapper">
            <div class="container-fluid">
                
                             Search by Column <div style="width:20%">
                                 <table>
                                     <tr>
                                         <th><asp:TextBox ID="TBsearch" runat="server" CssClass="form-control">

                                   </asp:TextBox></th>
                                         <th>
                                       <asp:ImageButton ID="Imgbtnsearch" runat="server" 
                                           ImageUrl="~/images/search.png" Width="20px" OnClick="Imgbtnsearch_Click" /></th>
                                     </tr>
                                 </table>
                             
                              </div>
                <br />
                     Select Entries:
                         <div class="dropdown">
                             <asp:DropDownList ID="DDLPagesize" runat="server" 
                                 OnSelectedIndexChanged="DDLPagesize_SelectedIndexChanged" AutoPostBack="true"> 
                       <asp:ListItem Selected="True" Text="--Select--" Value="--"></asp:ListItem>
                          <asp:ListItem Text="2" Value="2"></asp:ListItem>
                          <asp:ListItem Text="10" Value="10"></asp:ListItem>
                          <asp:ListItem Text="25" Value="20"></asp:ListItem>
                        <asp:ListItem Text="50" Value="10"></asp:ListItem>
                          <asp:ListItem Text="100" Value="20"></asp:ListItem>
                        <asp:ListItem Text="All" Value="All"></asp:ListItem>
                       </asp:DropDownList>
                        </div>
                         <!-- /input-group -->
                       
                    <asp:GridView runat="server" ID="GVMemberNotification" CellPadding="3" ForeColor="Black" GridLines="Vertical" BackColor="White" 
                        BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" Width="800px" AutoGenerateColumns="False"
                        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Memberid"   
                        onrowcancelingedit="GVMemberNotification_RowCancelingEdit" 
                         onrowediting="GVMemberNotification_RowEditing"   OnRowDataBound="GVMemberNotification_RowDataBound"
                        onrowupdating="GVMemberNotification_RowUpdating" AllowPaging="True" OnPageIndexChanging="GVMemberNotification_PageIndexChanging">
                        <AlternatingRowStyle BackColor="#CCCCCC" />
                        <Columns>
                            <asp:TemplateField HeaderText="Event Name" SortExpression="Event_Name">
                               
                                <ItemTemplate>
                                    <asp:Label ID="LBLEvent_Name" runat="server" Text='<%# Bind("Event_Name") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Family Name" SortExpression="FamilyName">
                                
                                <ItemTemplate>
                                    <asp:Label ID="LBLFamilyName" runat="server" Text='<%# Bind("FamilyName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Official Name" SortExpression="OfficialName">
                                
                                <ItemTemplate>
                                    <asp:Label ID="LBLOfficialName" runat="server" Text='<%# Bind("OfficialName") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            
                            <asp:TemplateField HeaderText="Proposed Date" SortExpression="ProposedDateOfBap">
                                <EditItemTemplate>
                                    <asp:TextBox ID="TBProposedDate" runat="server" Text='<%# Bind("ProposedDateOfBap") %>' ></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LBLProposedDateOfBap" runat="server" Text='<%# Bind("ProposedDateOfBap") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="Proposed Time" SortExpression="ProposedTimeOfBap">
                               <EditItemTemplate>
                                    <asp:TextBox ID="TBProposedTime" runat="server" Text='<%# Bind("ProposedTimeOfBap") %>' ></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LBLProposedTimeOfBap" runat="server" Text='<%# Bind("ProposedTimeOfBap") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                          
                            
                            <asp:TemplateField HeaderText="Description" SortExpression="RequestStatus_Description">
                              
                                <ItemTemplate>
                                    <asp:Label ID="LBLRequestStatus_Description" runat="server" Text='<%# Bind("RequestStatus_Description") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Status" SortExpression="RequestStatus">
                                 
                                <ItemTemplate>
                                    <asp:Label ID="LBLRequestStatus" runat="server" Text='<%# Bind("RequestStatus") %>' Visible="false"></asp:Label>
                                    <asp:Label ID="LBLRequestStatusLabel" runat="server" > </asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                           
                           </Columns>
                        <FooterStyle BackColor="#CCCCCC" />
                        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                        <SortedAscendingCellStyle BackColor="#F1F1F1" />
                        <SortedAscendingHeaderStyle BackColor="#808080" />
                        <SortedDescendingCellStyle BackColor="#CAC9C9" />
                        <SortedDescendingHeaderStyle BackColor="#383838" />
                    </asp:GridView>
                           </div>
               
            </div>
            <!-- /.container-fluid -->
        
    



</asp:Content>
