<%@ Page Title="" Language="C#" MasterPageFile="~/SubAdminMaster.Master" AutoEventWireup="true" CodeBehind="SubAdminHallRequest.aspx.cs" Inherits="Diocese.SubAdminHallRequest" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    
    <asp:GridView ID="GVHall" AutoGenerateColumns="False" runat="server" DataKeyNames="HallRequestId" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        onrowcancelingedit="GVHall_RowCancelingEdit"   onrowdeleting="GVHall_RowDeleting" 
        onrowediting="GVHall_RowEditing" onrowupdating="GVHall_RowUpdating" AllowPaging="true" OnPageIndexChanging="GVHall_PageIndexChanging"  BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" OnRowDataBound="GVHall_RowDataBound" >
       
        <Columns>
            
            <asp:TemplateField HeaderText="UserType" SortExpression="UserType">
               
                <ItemTemplate>
                    <asp:Label ID="Lblusertype" runat="server" Text='<%# Bind("UserType") %>' Visible="false"></asp:Label>
                     <asp:Label ID="Lbluser" runat="server"></asp:Label>

                </ItemTemplate>
            </asp:TemplateField>
           
            <asp:TemplateField HeaderText="EventName" SortExpression="EventName">
               
                <ItemTemplate>
                    <asp:Label ID="LblEventname" runat="server" Text='<%# Bind("EventName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Hall" SortExpression="HallName">
               
                <ItemTemplate>
                    <asp:Label ID="LblHall" runat="server" Text='<%# Bind("HallName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Official Name" SortExpression="OfficialName">
               
                <ItemTemplate>
                    <asp:Label ID="LblOfficialName" runat="server" Text='<%# Bind("OfficialName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="RequestDate" SortExpression="RequestDate">
               
                <ItemTemplate>
                    <asp:Label ID="LblRequestDate" runat="server" Text='<%# Bind("RequestDate") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
             <asp:TemplateField HeaderText="Status" SortExpression="Status">
               
                <ItemTemplate>
                    <asp:Label ID="LblStatus" runat="server" Text='<%# Bind("Status") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        <asp:TemplateField HeaderText="Description" SortExpression="Description">
               
                <ItemTemplate>
                    <asp:Label ID="LblDescription" runat="server" Text='<%# Bind("Description") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

        </Columns> 
        <FooterStyle BackColor="White" ForeColor="#000066" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
    </asp:GridView>
        
   </asp:Content>
