<%@ Page Title="" Language="C#" MasterPageFile="~/SubAdminMaster.Master" AutoEventWireup="true" CodeBehind="ViewAllWard.aspx.cs" Inherits="Diocese.ViewAllWard" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <div style="margin-left:10%;margin-top:10px">

  <%-- -------- search & user info start--%>
    
        <label style="color:white">Search by Column </label> <div style="width:20%">
                                 <table>
                                     <tr>
                                         <th><asp:TextBox ID="TBsearch" runat="server" CssClass="form-control search">

                                   </asp:TextBox></th><th>
                                       <asp:ImageButton ID="Imgbtnsearch" runat="server" OnClick="Imgbtnsearch_Click"
                                           ImageUrl="~/images/search.png" Width="20px"/></th>
                                     </tr>
                                 </table>
                             
                              </div>
        
                      <br />
                    <label style="color:white"> Select Entries:</label>
                         <div class="dropdown">
                             <asp:DropDownList ID="DDLPagesize" runat="server" 
                          OnSelectedIndexChanged="DDLPagesize_SelectedIndexChanged" AutoPostBack="true"> 
                       <asp:ListItem Selected="True" Text="--Select--" Value="--"></asp:ListItem>
                          <asp:ListItem Text="2" Value="2"></asp:ListItem>
                          <asp:ListItem Text="10" Value="10"></asp:ListItem>
                          <asp:ListItem Text="25" Value="20"></asp:ListItem>
                        <asp:ListItem Text="50" Value="10"></asp:ListItem>
                          <asp:ListItem Text="100" Value="20"></asp:ListItem>
                        <asp:ListItem Text="All" Value="All"></asp:ListItem>
                       </asp:DropDownList>
                        </div>


       <div style="margin-top:30px">
    <asp:GridView ID="GVWardTable" runat="server" AutoGenerateColumns="False" BackColor="White" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        onrowcancelingedit="GVWardTable_RowCancelingEdit"   onrowdeleting="GVWardTable_RowDeleting" 
        onrowediting="GVWardTable_RowEditing"   
        onrowupdating="GVWardTable_RowUpdating" AllowPaging="true" OnPageIndexChanging="GVWardTable_PageIndexChanging"
               
        BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" DataKeyNames="Ward_ID" 
        Width="400px" >
        <Columns>
              <asp:TemplateField HeaderText="Ward Name" SortExpression="WardName">
                <EditItemTemplate>
                    <asp:TextBox ID="TBWardName" runat="server" Text='<%# Bind("WardName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LBLWardNAme" runat="server" Text='<%# Bind("WardName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="White" ForeColor="#000066" />
        <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
        <RowStyle ForeColor="#000066" />
        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="#007DBB" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#00547E" />
    </asp:GridView>
            </div>
            </div>
   
</asp:Content>
