<%@ Page Title="" Language="C#" MasterPageFile="~/SubAdminMaster.Master" AutoEventWireup="true" CodeBehind="ViewParishHall.aspx.cs" Inherits="Diocese.ViewParishHall" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

     <div style="margin-top:30px">
    <asp:GridView ID="GVHallTable" runat="server" AutoGenerateColumns="False" BackColor="White" 
        AutoGenerateDeleteButton="True" AutoGenerateEditButton="True"
        onrowcancelingedit="GVHallTable_RowCancelingEdit"   onrowdeleting="GVHallTable_RowDeleting" 
        onrowediting="GVHallTable_RowEditing"   
        onrowupdating="GVHallTable_RowUpdating" AllowPaging="True" OnPageIndexChanging="GVHallTable_PageIndexChanging"
               
        BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" DataKeyNames="Hall_ID" 
        Width="800px"  ForeColor="Black" GridLines="Vertical" >
        <AlternatingRowStyle BackColor="#CCCCCC" />
        <Columns>
             <asp:TemplateField HeaderText="Hall Name" SortExpression="HallName">
                <EditItemTemplate>
                    <asp:TextBox ID="TBHallName" runat="server" Text='<%# Bind("HallName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LBLHallName" runat="server" Text='<%# Bind("HallName") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            
            <asp:BoundField DataField="HallNo" HeaderText="Hall Number" SortExpression="HallNo" />

            <asp:TemplateField HeaderText="No_of_people" SortExpression="No_of_people">
                <EditItemTemplate>
                    <asp:TextBox ID="TBPeopleCount" runat="server" Text='<%# Bind("No_of_people") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LBLPeopleCount" runat="server" Text='<%# Bind("No_of_people") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Rate" SortExpression="Rate">
                <EditItemTemplate>
                    <asp:TextBox ID="TBRate" runat="server" Text='<%# Bind("Rate") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="LBLRate" runat="server" Text='<%# Bind("Rate") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
        </Columns>
        <FooterStyle BackColor="#CCCCCC" />
        <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
        <SortedAscendingCellStyle BackColor="#F1F1F1" />
        <SortedAscendingHeaderStyle BackColor="Gray" />
        <SortedDescendingCellStyle BackColor="#CAC9C9" />
        <SortedDescendingHeaderStyle BackColor="#383838" />



        </asp:GridView>

        
</div>

</asp:Content>
